export { default as bottomBtn } from './subassembly/bottomBtn.vue';
export { default as goodsList } from './subassembly/goodsList.vue';
export { default as cartList } from './subassembly/cartList.vue';
export { default as loginFirst } from './subassembly/loginFirst.vue';
export { default as navBar } from './subassembly/navBar.vue';
export { default as phoneInput } from './subassembly/phoneInput.vue';
export { default as registerFirst } from './subassembly/registerFirst.vue';
export { default as Screen } from './subassembly/screen.vue';
export { default as verificationCode } from './subassembly/verificationCode.vue';
